# Generated by Django 4.2.5 on 2023-10-02 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('created_at',), 'verbose_name': 'تراکنش زرین\u200cپال', 'verbose_name_plural': 'تراکنش های زرین\u200cپال'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=64, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرجع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دلیل خطا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='آیا تراکنش آزمایشی است؟'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'تراکنش شروع شده است'), ('FAILED', 'تراکنش با خطا مواجه شد'), ('SUCCESS', 'نراکنش با موفقیت انجام شد')], default='PENDING', max_length=100, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
    ]
