# Generated by Django 4.2.5 on 2023-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_zarinpal', '0002_alter_transaction_options_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='کد پیگیری'),
        ),
    ]
